config/routes.rb
Rails.application.routes.draw do
  root "home#index"
  devise_for :users
  
  resources :users, only: [:show] do
    resources :posts, only: [:index, :show, :new, :create, :destroy]
  end

  

end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :user
  after_create :email_sponsor, :email_self

  private

  def email_sponsor
    NightlyMailer.sponsor_nightly(self).deliver
  end

  def email_self 
    NightlyMailer.self_nightly(self).deliver
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :posts
  devise :database_authenticatable, :recoverable, :registerable, :rememberable, :validatable
  after_create :sponsor_add_notification

  private

  def user_register_notification
    NightlyMailer.user_register(self).deliver
    @user = user
    @sponsor = @user.sponsor_email
    mail to: @user.email, subject: "You have registered for Nightly"
  end

  def sponsor_add_notification
    NightlyMailer.sponsor_add(self).deliver
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_up_path_for(resource)
    @user = User.find(resource.id)
    user_posts_path(@user)
  end

  def after_sign_in_path_for(resource)
    @user = User.find(resource.id)
    user_posts_path(@user)
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) << :sponsor_email
  end




end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  def index
    @user = User.find(params[:user_id])
  end

  def show
  end

  def new
    @post = Post.new
    @user = User.find(params[:user_id])
  end

  def create
    @post = Post.new(post_params)
    @user = User.find(params[:user_id])
    respond_to do |format|
      if @post.save
        format.html { redirect_to user_post_path(@user, @post), notice: 'Post was successfully created and emailed to your action partner.' }
      else
        format.html { render action: 'new' }
      end
    end
  end

  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to user_posts_path, notice: 'Post was successfully destroyed.' }
    end
  end

private

  def set_post
    @post = Post.find(params[:id])
  end

  def post_params
    params.require(:post).permit(:id, :resentful_at, :cause, :affects_my, :my_part, :selfish, :dishonest, :afraid, :owe_an_apology, :kept_to_myself, :kind_and_loving, :done_better, :thinking_of_myself, :thinking_of_others, :defects, :gratitude, :user_id)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/home/index.html.erb
<div class="jumbotron vertical-center">
  <h1 class="text-center">Welcome</h1>
  <p class="text-center">Nightly is a tool for drafting personal inventories and sharing them with an accountability partner.</p>
  <div class="text-center">
    <div class="alert alert-info" role="alert">
      <strong>Sorry</strong> Nightly is currently down for servicing until 3/31/17. Apologies for the inconvenience.
    </div>
    <!-- <%= link_to('  Enter  ', new_user_session_path, class: "btn btn-primary btn-lg") %><br> -->
    <br>
    Not a Nightly User?
    <%= link_to('Register', new_user_registration_path) %>
  </div>
</div>

app/views/layouts/_home_items.html.erb
<% if user_signed_in? %>
  <li>
  <%= link_to('Past Reviews', user_posts_path(current_user.id)) %>
  </li>
<% else %>
  <li>
  <%= link_to('Home', root_path)  %>
  </li>
<% end %>

app/views/layouts/_login_items.html.erb
<% if user_signed_in? %>
  <li>
  <%= link_to('Logout', destroy_user_session_path, :method => :delete) %>        
  </li>
<% else %>
  <li>
  <%= link_to('Login', new_user_session_path)  %>  
  </li>
<% end %>

app/views/layouts/_registration_items.html.erb
<% if user_signed_in? %>
  <li>
  <%= link_to('Edit Registration', edit_user_registration_path) %>
  </li>
<% else %>
  <li>
  <%= link_to('Register', new_user_registration_path)  %>
  </li>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Nightly</title>
  <link href='http://fonts.googleapis.com/css?family=Crimson+Text:400,400italic,600,700,600italic,700italic' rel='stylesheet' type='text/css'>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<div class="container-fluid">
  <div class="col-md-12">

  <nav>
    <div class="container-fluid">
      <div class="page-header">
        <h1><%= link_to "Nightly", root_path %></h1>
          <ul class="nav navbar-nav navbar-right">
            <%= render 'layouts/home_items' %>
            <%= render 'layouts/registration_items' %>
            <%= render 'layouts/login_items' %>
          </ul>
      </div>
    </div>
  </nav>
  <p><em>When we retire at night, we constructively review our day.</em></p>


  <%= yield %>
  </div>
</div>

</body>
</html>

app/views/posts/_form.html.erb
<div class="well well-lg">
      <legend>Review</legend>
      <%= form_for([@user, @post], url: user_posts_path, :html => {:class => "form"}) do |f| %>
            <div class="form-group input-group">
                  <span class="input-group-addon" id="basic-addon1"><%= f.label :resentful_at %></span>
                   <%= f.text_field :resentful_at, class:"form-control" %>
            </div>
            <div class="form-group input-group">
                  <span class="input-group-addon" id="basic-addon1"><%= f.label :cause %></span>
                   <%= f.text_field :cause, class:"form-control" %>
            </div>
            <div class="form-group input-group">
                  <span class="input-group-addon" id="basic-addon1"><%= f.label :affects_my %></span>
                   <%= f.text_field :affects_my, class:"form-control" %>
            </div>
            <div class="form-group input-group">
                  <span class="input-group-addon" id="basic-addon1"><%= f.label :my_part %></span>
                   <%= f.text_field :my_part, class:"form-control" %>
            </div>
            <div class="form-group input-group">
                  <span class="input-group-addon" id="basic-addon1"><%= f.label :selfish %></span>
                   <%= f.text_field :selfish, class:"form-control" %>
            </div>
            <div class="form-group input-group">
                  <span class="input-group-addon" id="basic-addon1"><%= f.label :dishonest %></span>
                   <%= f.text_field :dishonest, class:"form-control" %>
            </div>
            <div class="form-group input-group">
                  <span class="input-group-addon" id="basic-addon1"><%= f.label :afraid %></span>
                   <%= f.text_field :afraid, class:"form-control" %>
            </div>
            <div class="form-group input-group">
                  <span class="input-group-addon" id="basic-addon1"><%= f.label :owe_an_apology %></span>
                   <%= f.text_field :owe_an_apology, class:"form-control" %>
            </div>
            <div class="form-group input-group">
                  <span class="input-group-addon" id="basic-addon1"><%= f.label :kept_to_myself %></span>
                   <%= f.text_field :kept_to_myself, class:"form-control" %>
            </div>
            <div class="form-group input-group">
                  <span class="input-group-addon" id="basic-addon1"><%= f.label :kind_and_loving %></span>
                   <%= f.text_field :kind_and_loving, class:"form-control" %>
            </div>
            <div class="form-group input-group">
                  <span class="input-group-addon" id="basic-addon1"><%= f.label :kept_to_myself %></span>
                   <%= f.text_field :kept_to_myself, class:"form-control" %>
            </div>
            <div class="form-group input-group">
                  <span class="input-group-addon" id="basic-addon1"><%= f.label :done_better %></span>
                   <%= f.text_field :done_better, class:"form-control" %>
            </div>
            <div class="form-group input-group">
                  <span class="input-group-addon" id="basic-addon1"><%= f.label :thinking_of_myself %></span>
                   <%= f.text_field :thinking_of_myself, class:"form-control" %>
            </div>
            <div class="form-group input-group">
                  <span class="input-group-addon" id="basic-addon1"><%= f.label :thinking_of_others %></span>
                   <%= f.text_field :thinking_of_others, class:"form-control" %>
            </div>
            <div class="form-group input-group">
                  <span class="input-group-addon" id="basic-addon1"><%= f.label :defects %></span>
                   <%= f.text_field :defects, class:"form-control" %>
            </div>
            <div class="form-group input-group">
                  <span class="input-group-addon" id="basic-addon1"><%= f.label :gratitude %></span>
                   <%= f.text_field :gratitude, class:"form-control" %>
            </div>
            <%= f.hidden_field :user_id, :value => @user.id %>
            <div class="form-group input-group">
                  <div class="container">
                        <div class="row">
                              <%= link_to 'Cancel', user_posts_path, class: 'btn btn-default'%> 
                              <%= f.submit 'Submit', class: 'btn btn-primary' %>
                        </div>
                  </div>
            </div>
      <% end %>
      </form>
</div> <!-- well -->

app/views/posts/edit.html.erb
<% if flash[:notice] %>
  <div class="notice">
    <%= flash[:notice] %></p>
  </div>
<% end %>

<h3>Edit Date: <%= @post.created_at.strftime("%m/%d/%Y") %></h3>

<%= render 'form' %>

app/views/posts/index.html.erb
<h3>Past Reviews</h3>
<ul>
<% if @user.posts.length > 0 %>
     <% @user.posts.each do |post| %>
    <li><h4><%= link_to(post.created_at.strftime("%m/%d/%Y"), user_post_path(id: post.id)) %></h4></li>
  <% end %> 
<% else %>
  <li><em>No Posts Yet!</em></li>  
<% end %>
</ul>
<br>
<%= link_to 'New Review', new_user_post_path, :class => 'btn btn-default'%>

app/views/posts/new.html.erb
<h3>New Review</h3>

<%= render 'form' %>

app/views/posts/show.html.erb
<% if flash[:notice] %>
  <div class="notice">
    <%= flash[:notice] %></p>
  </div>
<% end %>


<h3>Date: <%= @post.created_at.strftime("%m/%d/%Y") %></h3>

<div class="well well-lg">
  <p> <strong>Resentful at:</strong> <%= @post.resentful_at %> <br>
  <strong>Cause:</strong> <%= @post.cause %> <br>
  <strong>Affects my:</strong> <%= @post.affects_my %> <br>
  <strong>My part:</strong> <%= @post.my_part %><br>
  <strong>Was I selfish?</strong> <%= @post.selfish %> <br>
  <strong>Dishonest?</strong> <%= @post.dishonest %> <br>
  <strong>Afraid?</strong> <%= @post.afraid %> <br>
  <strong>Do I owe an apology?</strong> <%= @post.owe_an_apology %> <br>
  <strong>Have I kept something to myself I should I have shared with another person?</strong> <%= @post.kept_to_myself %> <br>
  <strong>Was I kind and loving towards all? </strong><%= @post.kind_and_loving %> <br>
  <strong>What could I have done better?</strong> <%= @post.done_better %> <br>
  <strong>Was I thinking only of myself?</strong> <%= @post.thinking_of_myself %> <br>
  <strong>Or, was I thinking about what I could do for others?</strong> <%= @post.thinking_of_others %> <br>
  <strong>What character defects did I exhibit today?</strong> <%= @post.defects %> <br>
  <strong>For what am I grateful?</strong> <%= @post.gratitude %> <br>
  </p>
</div>

<%= link_to 'Share with Sponsor', user_posts_path(@post.user), :class => 'btn btn-success'%>  <%= link_to 'Destroy', user_post_path, method: :delete, data: { confirm: 'Are you sure?' }, :class => 'btn btn-danger' %>  <%= link_to 'Done', user_posts_path(@post.user), :class => 'btn btn-default'%> 